name: reviewdog
on: [pull_request]
jobs:
  markuplint:
    name: runner / markuplint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - "18"
          - "20"
          - "22"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: markuplint-github-pr-check
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: info
      - name: markuplint-github-check
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
      - name: markuplint-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
      - name: markuplint-subproject-github-pr-review
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: ./test-subproject
      - name: markuplint-subproject
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: ./test-subproject
          reporter: github-check
          level: warning
          filter_mode: file
